name: Build Solana BPF Program

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions/setup-rust@v1
      with:
        rust-version: nightly

    - name: Install Solana CLI
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://release.solana.com/v1.10.32/solana-release-x86_64-unknown-linux-gnu.tar.bz2 | tar -xvjf - -C $HOME/.cargo/bin
        solana --version

    - name: Install dependencies
      run: |
        cargo install --locked cross

    - name: Build BPF Program
      run: |
        cross build --target bpfel-unknown-unknown --release

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: solana-bpf-program
        path: target/bpfel-unknown-unknown/release/my_token.so
